// <auto-generated />
using Infrastructure.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.12");

            modelBuilder.Entity("Domain.Models.Guild", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<ulong>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RankingTypes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("guild", (string)null);
                });

            modelBuilder.Entity("Domain.Models.User", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DiscordNickName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GameNickName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRanked")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kills")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ThumbUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("WinRate")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.ToTable("user", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 385869185198063626ul,
                            DiscordNickName = "Cleiton Furst",
                            GameNickName = "Jhpo",
                            GuildId = 1038639386646032415ul,
                            IsRanked = true,
                            Kills = 640,
                            ThumbUrl = "https://cdn.discordapp.com/embed/avatars/0.png?size=1024",
                            WinRate = 12.199999999999999
                        },
                        new
                        {
                            Id = 926292122842312795ul,
                            DiscordNickName = "camargooo",
                            GameNickName = "Faker171",
                            GuildId = 1038639386646032415ul,
                            IsRanked = true,
                            Kills = 99,
                            ThumbUrl = "https://cdn.discordapp.com/embed/avatars/0.png?size=1024",
                            WinRate = 0.5
                        },
                        new
                        {
                            Id = 1134185785617293402ul,
                            DiscordNickName = "yuru44",
                            GameNickName = "Oyurii",
                            GuildId = 1038639386646032415ul,
                            IsRanked = true,
                            Kills = 93,
                            ThumbUrl = "https://cdn.discordapp.com/embed/avatars/0.png?size=1024",
                            WinRate = 10.0
                        },
                        new
                        {
                            Id = 732999507331252246ul,
                            DiscordNickName = "VicManzas",
                            GameNickName = "manzass",
                            GuildId = 1038639386646032415ul,
                            IsRanked = true,
                            Kills = 117,
                            ThumbUrl = "https://cdn.discordapp.com/embed/avatars/0.png?size=1024",
                            WinRate = 45.799999999999997
                        });
                });

            modelBuilder.Entity("Domain.Models.User", b =>
                {
                    b.HasOne("Domain.Models.Guild", "Guild")
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");
                });
#pragma warning restore 612, 618
        }
    }
}
